### PR TITLE
Question on how to do regex checks for cron entries

### PR DESCRIPTION
**Pull request by ghoneycutt**
Thank you very much for writing serverspec! I've been spreading the word at many conferences and have ran into a problem.

### CODE REVIEW

**Comment by mizzy** [comment]
You can get all cron table entries and use rexexp like this:

```ruby
describe cron do
  its(:table) { should match  /you can use regexp/ }
end
```

Sorry, I forget to document it.

**Comment by ghoneycutt** [comment]
Thank you very much! If you could point me toward the repo with the web site, I'll be happy to send a PR to update the docs.

**Comment by mizzy** [comment]
>  I'll be happy to send a PR to update the docs.

Thanks! The repo is https://github.com/serverspec/serverspec.github.io .

**Comment by bcorner13** [comment]
This doesn't work for entries created with the crond chef resource.  Those entries get put in /etc/cron.d/<name>.

**Comment by mizzy** [comment]
Patches are welcome.

**Pull request closed without merging**
