### PR TITLE
Bump specinfra gem from 2.53 to 2.59.6

### PR DESCRIPTION
**Pull request by jules2689**
I pulled the full change log out of the [releases for specinfra](https://github.com/mizzy/specinfra/releases), I'm specifically bumping for the latest change I had merged there. We found that some tests failed when asserting that `homebrew_cask` installed some brew packages and a fix was put into specinfra. 

Changes
---
- Cask now uses 2 separate potential files locations
- Ignore "system_user" option for user creation on FreeBSD.
- Check if kernel module is loaded on Solaris
- Add protocol options to darwin port listening check
- Fix subclasses singleton_class check
- pip and gem check_is_installed false successes
- host_inventory: use kenv to get the system product name on FreeBSD
- Added default task to run rake spec:all
- Fix mail_alias_spec filename
- Isolate specs so the whole suite can be run
- host_inventory: use systemd-detect-virt for virtualization detection
- Support host_inventory['group']
- Add check that symlinks can be fully resolved to their real path
- Support host_inventory['user']
- Support the init system for Alpine Linux
- Use sed instead of grep and cut
- Close communication pipes after process finished
- Use cut instead of awk
- Support Ubuntu v16.xx
- Add support for Cygwin
- Support fluentd plugin installed check command
- Consume remained stdout and stderr from buffer
- multiple commands needs to be executes as $(commands)
- Allowing the use of net-ssh < 4.0 if using Ruby 2.0+
- SLES 12 Support
- Use Write-Host instead of Out-String for Windows file content
- Docker backend accepts send_file when base_image isn't set, but container is set
- Add options to Command::Base::File
- Return $TRUE and $FALSE in Windows is_owned_by command
- Allow backslash in crontab

### CODE REVIEW

**Comment by mizzy** [comment]
You should do this on your Gemfile.

**Comment by jules2689** [comment]
@mizzy I do not see how my local Gemfile affects a production release of this file, which relies on the gemspec. My local Gemfile is up to date, but the gemspec should be updated and a new version released to accommodate the bugfixes in specinfra. no?

**Comment by mizzy** [comment]
Serverspec does not depend on 2.59.6 strictly. It works with specinfra >= 2.53.
So it is not proper to fix gemspec of serverspec.

If you'd like to use latest version of specinfra, you write it in your Gemfile.

Users should be free to choose the version of specinfra, even if the version has bugs.
And the bug about homebrew_cask does not affect users who do not use MacOS.

**Comment by jules2689** [comment]
Fair, The `~>` notation confuses me sometimes. sorry bout the confusion there

**Comment by mizzy** [comment]
> The ~> notation confuses me sometimes

Me too.

> sorry bout the confusion there

No problem 😃  Thanks for reporting.

**Pull request closed without merging**
