### PR TITLE
fix appveyor fails

### PR DESCRIPTION
**Pull request by sawanoboly**
same as https://github.com/mizzy/specinfra/pull/578

### CODE REVIEW

**Comment by StefanScherer** [comment]
@sawanoboly Thank you. This commit helped me making my serverspec tests work again in AppVeyor.

It seems to me that the problem is the new PowerShell 5. I've seen this issue in Vagrant and Packer as well. How could be serverspec fixed to work with PowerShell 5 as this PR seems to be a workaround, using the previous version of AppVeyor's build image?

Has it to do something with a missing `$ProgressPreference = 'SilentlyContinue'` or using  winrm v2 ruby gem as mentioned in https://github.com/mefellows/vagrant-dsc/issues/21#issuecomment-235972484 ?

Sorry, I don't know all the details how serverspec/rspec runs the windows tests locally. I just use

```ruby
set :backend, :cmd
set :os, :family => 'windows'
```

**Comment by sawanoboly** [comment]
@StefanScherer 

I seem that it is Powershell 5.0's bug. Probably 5.1 or later doesn't cause it.

FYI, we have conversation about similar issue in below topic.

http://help.appveyor.com/discussions/problems/5170-progresspreference-not-works-always-shown-preparing-modules-for-first-use-in-stderr

**Comment by StefanScherer** [comment]
@sawanoboly Thank you for the link! So AppVeyor is investigating the problem as well.

As far as I understood the discussion in packer and vagrant was that PowerShell has another stream for progress, not just stdin and stderr. And that gets mixed into the other streams.

**Comment by mizzy** [comment]
Sorry, I missed this pull request. Thanks!

**Comment by mizzy** [comment]
Released as v2.37.0.

**Comment by StefanScherer** [comment]
Using the previous AppVeyor image does not work any longer for us. We use this workaround at the moment to add `-NoProfile -encodedCommand` to specinfra.

```powershell
Write-Host "Patching specinfra for AppVeyor"
(Get-Content vendor\bundle\ruby\2.2.0\gems\specinfra-2.63.1\lib\specinfra\backend\cmd.rb) |
  Foreach-Object {$_ -replace '-encodedCommand', '-NoProfile -encodedCommand'} |
  Out-File -Encoding ascii vendor\bundle\ruby\2.2.0\gems\specinfra-2.63.1\lib\specinfra\backend\cmd.rb
```

**Comment by StefanScherer** [comment]
See also PR https://github.com/mizzy/specinfra/pull/584

**Pull request merged**
