### PR TITLE
Added more modern ruby versions to the build

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
Looks like AppVeyor doesn't support 2.3 yet.
Should I remove the build job for now?

**Comment by sawanoboly** [comment]
Hi,

AppVeyor uses http://rubyinstaller.org to install rubies. Please remove for now. I'll add 2.3 when it is available on AppVeyor.

**Comment by thedrow** [comment]
Done.

**Comment by mizzy** [comment]
Thanks!

**Comment by thedrow** [comment]
RubyInstaller just shipped with 2.3 https://github.com/oneclick/rubyinstaller/issues/302#issuecomment-205620480
Should I issue a new PR?

**Comment by sawanoboly** [comment]
@thedrow 

I think it's good. How about you, @mizzy ?

**Comment by mizzy** [comment]
@thedrow @sawanoboly Yes, please! Thanks!

**Comment by mizzy** [comment]
Released as v2.32.0.

**Pull request merged**
