### PR TITLE
Changed expectations to be more fine-grained to remove warning notices when running tests; Added tests and refactored setup.rb

### PR DESCRIPTION
**Pull request by ihassin**
Modified expectation syntax to remove warnings when running tests.

### CODE REVIEW

**Comment by ihassin** [comment]
Sorry about these messy commits. Basically this PR is:
1. No more warnings when running rSpec (fixed expectations when expecting exceptions)
2. Added tests for setup.rb
3. Refactored setup.rb as a first step in my wish to modify it to accept command-line params in addition to the interactive mode (menu, user input).
4. Messed around with suppressing stdout in rSpec, but removed it since some calls were incompatible with 1.8.7. Thanks Travis!

Anyway, I will make sure to have cleaner commits and PRs in the future.
Thanks!
Itamar

**Comment by ihassin** [comment]
Hi Mizzy,

Please tell me which part you're against:

1. Fixing the warnings caused by some rSpecs?
2. Adding tests to setup.rb and refactoring some functions there?

I'll adapt accordingly,

Thanks,
Itamar

**Comment by mizzy** [comment]
So many topics in one pull request. Please include one topic in one pull request.

**Comment by ihassin** [comment]
Got it, will do.

**Comment by mizzy** [comment]
>  3. Refactored setup.rb as a first step in my wish to modify it to accept command-line params in addition to the interactive mode (menu, user input).

Refactoring is good, but I will not add a function to accept command-line params. serverspec-init is for generating example files for beginners. If you like to customize these files, you should edit these files directly.

**Pull request closed without merging**
