### PR TITLE
Added Ruby 2.3 to Appveyor build

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
Not sure why AppVeyor didn't download the new ruby version?
Do they have to make a new image?

**Comment by sawanoboly** [comment]
I've created ticket to resolve this to appveyor. http://help.appveyor.com/discussions/questions/2224-ruby-23

Please wait their response.

**Comment by sawanoboly** [comment]
I'll retry test after Apr 10 📆  https://github.com/appveyor/ci/milestones/apr-10

**Comment by sawanoboly** [comment]
https://ci.appveyor.com/project/serverspec-windows-integration-test/serverspec/build/110/job/l5wxy69f8of33oxp

```
ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [i386-mingw32]
gem --version
2.6.3
```
OK, it's ready to merge 💚  @thedrow @mizzy

**Comment by mizzy** [comment]
OK, thanks!

**Comment by mizzy** [comment]
Released as v2.32.0.

**Pull request merged**
