### PR TITLE
add resource type json file

### PR DESCRIPTION
**Pull request by takaishi**
I want to test json file (for example, consul config file) by include matcher with serverspec.

```
describe json_file('foo.json') do
  its(:content) { should include('foo' => include('bar' => 'hoge')) }
end
```

### CODE REVIEW

**Comment by mizzy** [comment]
`json_file` would be better. Could you please fix it ?

**Comment by takaishi** [comment]
Thank you comment.
I fixed it !

**Comment by mizzy** [comment]
Thanks!

**Comment by mizzy** [comment]
Released as v2.33.0.

**Pull request merged**
